// src/lib/arizonaAirports.ts
//
// Hub-only directory for /airports. These entries render as rows on the
// hub page and NEVER generate their own pages — money pages live in
// airportsData (src/lib/airports.ts). Keep it that way: one thin page
// per tiny airfield is exactly the pattern Google demoted in June.
//
// Source: FAA NPIAS 2023–2027 roles and CY2024 enplanements (via the
// Wikipedia "List of airports in Arizona"). Drive times are approximate
// from central Phoenix and are for orientation, not quotes.

export type DirectoryGroup = "commercial" | "reliever" | "regional";

export type DirectoryAirport = {
  name: string;
  city: string;
  faa: string;
  iata?: string;
  icao?: string;
  group: DirectoryGroup;
  role: string; // human label for the FAA category
  enplanements?: number; // CY2024 commercial boardings, where recorded
  driveFromPhoenix?: string; // approx., from central Phoenix
  note?: string; // one line: what it is / what we do there
  href?: string; // where "Book a ride" or the name should link, if anywhere
};

export const DIRECTORY_GROUPS: {
  key: DirectoryGroup;
  heading: string;
  blurb: string;
}[] = [
  {
    key: "commercial",
    heading: "Commercial Airports in Arizona",
    blurb:
      "Eight Arizona airports have scheduled airline service. Sky Harbor carries the overwhelming majority of passengers; Tucson and Mesa Gateway are the only others above a million boardings a year.",
  },
  {
    key: "reliever",
    heading: "Private Aviation & Reliever Airports",
    blurb:
      "FAA-designated reliever airports around Phoenix and Tucson — no airline counters, but this is where private jets, charters, and corporate flight departments land. We meet these flights at the FBO.",
  },
  {
    key: "regional",
    heading: "Regional & General Aviation Airports",
    blurb:
      "The rest of the state's public-use airports in the national system — county fields, tourism strips, and desert airparks. We run long-distance transfers to the ones people actually travel to and quote the rest on request.",
  },
];

export const arizonaAirportsDirectory: readonly DirectoryAirport[] = [
  /* ── Commercial service ─────────────────────────────────────────── */
  {
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    faa: "PHX",
    iata: "PHX",
    icao: "KPHX",
    group: "commercial",
    role: "Commercial – large hub",
    enplanements: 25595723,
    driveFromPhoenix: "10–35 min across the Valley",
    note: "Arizona's primary airport — Terminals 3 & 4, every major airline. Our most-driven route since 2004.",
    href: "/airports/phx-sky-harbor",
  },
  {
    name: "Tucson International Airport",
    city: "Tucson",
    faa: "TUS",
    iata: "TUS",
    icao: "KTUS",
    group: "commercial",
    role: "Commercial – small hub",
    enplanements: 1959789,
    driveFromPhoenix: "1 hr 45 min",
    note: "Southern Arizona's airline gateway. Phoenix–Tucson and airport-to-airport transfers daily.",
    href: "/airports/tucson-international",
  },
  {
    name: "Mesa Gateway Airport",
    city: "Mesa",
    faa: "IWA",
    iata: "AZA",
    icao: "KIWA",
    group: "commercial",
    role: "Commercial – small hub",
    enplanements: 978296,
    driveFromPhoenix: "35–45 min",
    note: "The East Valley's airport — Allegiant and Sun Country, cheap parking, short lines.",
    href: "/airports/mesa-gateway",
  },
  {
    name: "Yuma International Airport",
    city: "Yuma",
    faa: "NYL",
    iata: "YUM",
    icao: "KNYL",
    group: "commercial",
    role: "Commercial – nonhub",
    enplanements: 85227,
    driveFromPhoenix: "2 hr 45 min",
    note: "Shares runways with MCAS Yuma. Long-distance transfers to and from the Valley.",
    href: "/locations/yuma",
  },
  {
    name: "Flagstaff Pulliam Airport",
    city: "Flagstaff",
    faa: "FLG",
    iata: "FLG",
    icao: "KFLG",
    group: "commercial",
    role: "Commercial – nonhub",
    enplanements: 79081,
    driveFromPhoenix: "2 hr 15 min",
    note: "Northern Arizona's commercial airport — Grand Canyon and Snowbowl traffic. Phoenix–Flagstaff runs in any season.",
    href: "/routes/flagstaff-to-phoenix",
  },
  {
    name: "Prescott Municipal Airport (Ernest A. Love Field)",
    city: "Prescott",
    faa: "PRC",
    iata: "PRC",
    icao: "KPRC",
    group: "commercial",
    role: "Commercial – nonhub",
    enplanements: 25316,
    driveFromPhoenix: "1 hr 45 min",
    note: "Limited airline service plus a busy training and private-aviation field. Phoenix–Prescott transfers.",
    href: "/routes/phoenix-to-prescott",
  },
  {
    name: "Page Municipal Airport",
    city: "Page",
    faa: "PGA",
    iata: "PGA",
    icao: "KPGA",
    group: "commercial",
    role: "Commercial – nonhub",
    enplanements: 22400,
    driveFromPhoenix: "4 hr 30 min",
    note: "Lake Powell and Antelope Canyon access. Long-distance transfers by quote.",
  },
  {
    name: "Show Low Regional Airport",
    city: "Show Low",
    faa: "SOW",
    iata: "SOW",
    icao: "KSOW",
    group: "commercial",
    role: "Commercial – nonprimary",
    enplanements: 3655,
    driveFromPhoenix: "3 hr",
    note: "White Mountains gateway with limited scheduled service. Long-distance transfers by quote.",
  },

  /* ── Reliever / private aviation ────────────────────────────────── */
  {
    name: "Scottsdale Airport",
    city: "Scottsdale",
    faa: "SDL",
    iata: "SCF",
    icao: "KSDL",
    group: "reliever",
    role: "Reliever",
    enplanements: 46524,
    driveFromPhoenix: "20 min to Old Town, 25 min to downtown Phoenix",
    note: "One of the busiest private-aviation airports in the country, plus JSX's semi-private flights. FBO and terminal pickups.",
    href: "/airports/scottsdale-airport",
  },
  {
    name: "Phoenix Deer Valley Airport",
    city: "Phoenix",
    faa: "DVT",
    iata: "DVT",
    icao: "KDVT",
    group: "reliever",
    role: "Reliever",
    enplanements: 102,
    driveFromPhoenix: "25 min to downtown, 25 min to Scottsdale",
    note: "North Phoenix's private-aviation and flight-training hub at I-17 and the Loop 101. FBO pickups at Cutter Aviation.",
    href: "/airports/deer-valley",
  },
  {
    name: "Falcon Field",
    city: "Mesa",
    faa: "FFZ",
    iata: "MSC",
    icao: "KFFZ",
    group: "reliever",
    role: "Reliever",
    enplanements: 17,
    driveFromPhoenix: "30 min",
    note: "Northeast Mesa — corporate aircraft, a major flight academy, and Boeing's Mesa facility next door. FBO pickups.",
    href: "/airports/private-aviation",
  },
  {
    name: "Chandler Municipal Airport",
    city: "Chandler",
    faa: "CHD",
    iata: "CHD",
    icao: "KCHD",
    group: "reliever",
    role: "Reliever",
    enplanements: 42,
    driveFromPhoenix: "30 min",
    note: "South Chandler, minutes from the Price Road tech corridor. FBO pickups for corporate and charter flights.",
    href: "/airports/private-aviation",
  },
  {
    name: "Glendale Municipal Airport",
    city: "Glendale",
    faa: "GEU",
    icao: "KGEU",
    group: "reliever",
    role: "Reliever",
    enplanements: 36,
    driveFromPhoenix: "25 min",
    note: "West Valley business jets, ten minutes from State Farm Stadium and Westgate. FBO pickups on event weekends.",
    href: "/airports/private-aviation",
  },
  {
    name: "Phoenix Goodyear Airport",
    city: "Goodyear",
    faa: "GYR",
    iata: "GYR",
    icao: "KGYR",
    group: "reliever",
    role: "Reliever",
    enplanements: 8,
    driveFromPhoenix: "30 min",
    note: "Long runway on the I-10 corridor — corporate jets and airline training. FBO pickups.",
    href: "/airports/private-aviation",
  },
  {
    name: "Marana Regional Airport",
    city: "Marana (near Tucson)",
    faa: "AVQ",
    iata: "AVW",
    icao: "KAVQ",
    group: "reliever",
    role: "Reliever",
    enplanements: 14,
    driveFromPhoenix: "1 hr 30 min",
    note: "Northwest Tucson's private-aviation field, near the Ritz-Carlton Dove Mountain.",
  },
  {
    name: "Ryan Airfield",
    city: "Tucson",
    faa: "RYN",
    iata: "RYN",
    icao: "KRYN",
    group: "reliever",
    role: "Reliever",
    driveFromPhoenix: "2 hr",
    note: "Tucson's southwest-side general aviation reliever.",
  },

  /* ── Regional / general aviation ────────────────────────────────── */
  {
    name: "Grand Canyon National Park Airport",
    city: "Grand Canyon (Tusayan)",
    faa: "GCN",
    iata: "GCN",
    icao: "KGCN",
    group: "regional",
    role: "General aviation",
    enplanements: 120222,
    driveFromPhoenix: "3 hr 45 min",
    note: "Air tours and charters at the South Rim. Phoenix–Grand Canyon transfers by quote.",
    href: "/services/long-distance-drives",
  },
  {
    name: "Laughlin/Bullhead International Airport",
    city: "Bullhead City",
    faa: "IFP",
    iata: "IFP",
    icao: "KIFP",
    group: "regional",
    role: "General aviation",
    enplanements: 68837,
    driveFromPhoenix: "3 hr 30 min",
    note: "Casino charter traffic across the river from Laughlin, Nevada.",
  },
  {
    name: "Grand Canyon West Airport",
    city: "Peach Springs",
    faa: "1G4",
    iata: "GCW",
    group: "regional",
    role: "General aviation",
    enplanements: 29597,
    driveFromPhoenix: "3 hr 45 min",
    note: "Skywalk and Hualapai air-tour traffic on the West Rim.",
  },
  {
    name: "Sedona Airport",
    city: "Sedona",
    faa: "SEZ",
    iata: "SDX",
    icao: "KSEZ",
    group: "regional",
    role: "General aviation",
    enplanements: 62,
    driveFromPhoenix: "2 hr",
    note: "A mesa-top runway with scenic flights and private jets — no airline service. Phoenix–Sedona transfers daily.",
    href: "/routes/phoenix-to-sedona",
  },
  {
    name: "Lake Havasu City Airport",
    city: "Lake Havasu City",
    faa: "HII",
    iata: "HII",
    icao: "KHII",
    group: "regional",
    role: "General aviation",
    enplanements: 17,
    driveFromPhoenix: "3 hr 15 min",
  },
  {
    name: "Kingman Airport",
    city: "Kingman",
    faa: "IGM",
    iata: "IGM",
    icao: "KIGM",
    group: "regional",
    role: "General aviation",
    enplanements: 209,
    driveFromPhoenix: "2 hr 45 min",
  },
  {
    name: "Payson Airport",
    city: "Payson",
    faa: "PAN",
    iata: "PJB",
    icao: "KPAN",
    group: "regional",
    role: "General aviation",
    enplanements: 3,
    driveFromPhoenix: "1 hr 30 min",
    note: "Rim Country's airstrip. Phoenix–Payson transfers.",
    href: "/locations/payson",
  },
  {
    name: "Wickenburg Municipal Airport",
    city: "Wickenburg",
    faa: "E25",
    iata: "E25",
    group: "regional",
    role: "General aviation",
    enplanements: 2,
    driveFromPhoenix: "1 hr",
    note: "Dude-ranch and rodeo country. Phoenix–Wickenburg transfers.",
    href: "/locations/wickenburg",
  },
  {
    name: "Casa Grande Municipal Airport",
    city: "Casa Grande",
    faa: "CGZ",
    iata: "CGZ",
    icao: "KCGZ",
    group: "regional",
    role: "General aviation",
    enplanements: 2,
    driveFromPhoenix: "50 min",
    note: "Midway between Phoenix and Tucson on I-10.",
    href: "/locations/casa-grande",
  },
  {
    name: "Buckeye Municipal Airport",
    city: "Buckeye",
    faa: "BXK",
    iata: "BXK",
    icao: "KBXK",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "45 min",
    href: "/locations/buckeye",
  },
  {
    name: "Ak-Chin Regional Airport",
    city: "Maricopa",
    faa: "A39",
    iata: "A39",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "45 min",
    href: "/locations/maricopa",
  },
  {
    name: "Pinal Airpark",
    city: "Marana",
    faa: "MZJ",
    iata: "MZJ",
    icao: "KMZJ",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "1 hr 15 min",
    note: "The airliner storage field you see from I-10.",
  },
  {
    name: "Sierra Vista Municipal Airport / Libby AAF",
    city: "Sierra Vista / Fort Huachuca",
    faa: "FHU",
    iata: "FHU",
    icao: "KFHU",
    group: "regional",
    role: "General aviation",
    enplanements: 178,
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Nogales International Airport",
    city: "Nogales",
    faa: "OLS",
    iata: "OLS",
    icao: "KOLS",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Safford Regional Airport",
    city: "Safford",
    faa: "SAD",
    iata: "SAD",
    icao: "KSAD",
    group: "regional",
    role: "General aviation",
    enplanements: 63,
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Winslow–Lindbergh Regional Airport",
    city: "Winslow",
    faa: "INW",
    iata: "INW",
    icao: "KINW",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr 15 min",
  },
  {
    name: "Cottonwood Airport",
    city: "Cottonwood",
    faa: "P52",
    iata: "CTW",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "1 hr 45 min",
    note: "Verde Valley wine country, minutes from Sedona.",
  },
  {
    name: "Bisbee Douglas International Airport",
    city: "Douglas / Bisbee",
    faa: "DUG",
    iata: "DUG",
    icao: "KDUG",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr 45 min",
  },
  {
    name: "H.A. Clark Memorial Field",
    city: "Williams",
    faa: "CMR",
    iata: "CMR",
    icao: "KCMR",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "2 hr 45 min",
    note: "Grand Canyon Railway town.",
  },
  {
    name: "Eloy Municipal Airport",
    city: "Eloy",
    faa: "E60",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "1 hr",
    note: "Home of Skydive Arizona.",
  },
  {
    name: "Coolidge Municipal Airport",
    city: "Coolidge",
    faa: "P08",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "1 hr",
  },
  {
    name: "Gila Bend Municipal Airport",
    city: "Gila Bend",
    faa: "E63",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "1 hr 15 min",
  },
  {
    name: "San Carlos Apache Airport",
    city: "Globe",
    faa: "P13",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "1 hr 30 min",
  },
  {
    name: "Greenlee County Airport",
    city: "Clifton / Morenci",
    faa: "CFT",
    iata: "CFT",
    icao: "KCFT",
    group: "regional",
    role: "General aviation",
    enplanements: 68,
    driveFromPhoenix: "3 hr 15 min",
  },
  {
    name: "Bagdad Airport",
    city: "Bagdad",
    faa: "E51",
    iata: "BGT",
    group: "regional",
    role: "General aviation",
    enplanements: 79,
    driveFromPhoenix: "2 hr 15 min",
  },
  {
    name: "Eric Marcus Municipal Airport",
    city: "Ajo",
    faa: "P01",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "2 hr 15 min",
  },
  {
    name: "Benson Municipal Airport",
    city: "Benson",
    faa: "E95",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "2 hr 30 min",
  },
  {
    name: "Bisbee Municipal Airport",
    city: "Bisbee",
    faa: "P04",
    iata: "BSQ",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr 30 min",
  },
  {
    name: "Colorado City Municipal Airport",
    city: "Colorado City",
    faa: "AZC",
    icao: "KAZC",
    group: "regional",
    role: "General aviation",
    enplanements: 96,
    driveFromPhoenix: "5 hr 30 min",
  },
  {
    name: "Chinle Municipal Airport",
    city: "Chinle",
    faa: "E91",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "5 hr",
  },
  {
    name: "Cibecue Airport",
    city: "Cibecue",
    faa: "Z95",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Holbrook Municipal Airport",
    city: "Holbrook",
    faa: "P14",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Kayenta Airport",
    city: "Kayenta",
    faa: "0V7",
    iata: "MVM",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "5 hr",
    note: "Monument Valley's airstrip.",
  },
  {
    name: "Avi Suquilla Airport",
    city: "Parker",
    faa: "P20",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "2 hr 45 min",
  },
  {
    name: "Polacca Airport",
    city: "Polacca",
    faa: "P10",
    iata: "PXL",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "4 hr",
  },
  {
    name: "San Manuel Airport",
    city: "San Manuel",
    faa: "E77",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "2 hr",
  },
  {
    name: "Springerville Municipal Airport",
    city: "Springerville",
    faa: "JTC",
    icao: "KJTC",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "4 hr",
  },
  {
    name: "St. Johns Industrial Air Park",
    city: "St. Johns",
    faa: "SJN",
    iata: "SJN",
    icao: "KSJN",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr 45 min",
  },
  {
    name: "Taylor Airport",
    city: "Taylor",
    faa: "TYL",
    iata: "TYZ",
    icao: "KTYL",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Tuba City Airport",
    city: "Tuba City",
    faa: "T03",
    iata: "TBC",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "4 hr",
  },
  {
    name: "Whiteriver Airport",
    city: "Whiteriver",
    faa: "E24",
    iata: "WTR",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr 15 min",
  },
  {
    name: "Cochise County Airport",
    city: "Willcox",
    faa: "P33",
    iata: "P33",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "3 hr",
  },
  {
    name: "Window Rock Airport",
    city: "Window Rock",
    faa: "RQE",
    iata: "RQE",
    icao: "KRQE",
    group: "regional",
    role: "General aviation",
    driveFromPhoenix: "5 hr",
    note: "Navajo Nation capital.",
  },
];

/** Count of public-use airports in the national system (this list). */
export const NPIAS_AIRPORT_COUNT = arizonaAirportsDirectory.length;
